name: "external API action"

description: "use an external API to retrieve data and display a joke"

outputs:
  joke-output:
    description: The resulting joke from the icanhazdadjokes API

runs:
  using: "node12"
  main: "main.js"